display_name: AbuJena Dawajen 
publisher_display_name: AbuJena Co
publisher: CN=AbuJena, O=AbuJena, L=Cairo, S=Cairo, C=EG 
install_certificate: false
identity_name: com.abujena.dawajen
msix_version: 1.0.0.0
logo_path: assets/logos/logo.jpg
capabilities: internetClient, location, microphone, webcam