name: Distribute Desktop
on:
    push:
        branches: [prod, dev]
permissions:
    contents: write
    packages: write
jobs:
    build_desktop:
        runs-on: windows-latest
        environment: ${{ github.ref_name }}
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
            - run: flutter config --enable-windows-desktop
            - run: flutter pub get
            - run: flutter build windows --release --dart-define=ENV=${{ github.ref_name }}
            - run: dart run msix:create
            - uses: actions/upload-artifact@v4
              with:
                  path: build/windows/x64/runner/Release/*.msix
            - uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/windows/x64/runner/Release/*.msix
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: softprops/action-gh-release@v2
              with:
                  tag_name: latest
                  files: build/windows/x64/runner/Release/*.msix
                  body: "احدث نسخة"
                  prerelease: false
                  make_latest: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
