name: Clean Previous Releases
on:
  workflow_run:
    workflows: ["Deploy App (Multi-Environment)"]
    types: [completed]
jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/checkout@v4
      - id: restore_flag
        uses: actions/cache/restore@v4
        with:
          path: release_flag.txt
          key: cache-release-flag-${{ github.event.workflow_run.id }}
      - uses: google-github-actions/auth@v2
        if: steps.restore_flag.outputs.cache-hit == 'true'
        with:
          credentials_json: ${{ secrets.FIREBASE_ADMIN_SDK }}
      - if: steps.restore_flag.outputs.cache-hit == 'true'
        id: get_token
        run: |
          echo "token=$(gcloud auth print-access-token)" >> $GITHUB_OUTPUT
      - if: steps.restore_flag.outputs.cache-hit == 'true'
        env:
          FIREBASE_PROJECT_NUMBER: ${{ vars.FIREBASE_PROJECT_NUMBER }}""
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
        run: |
          pip install requests
          python .github/scripts/cleanup_firebase.py
