name: Dev Distribute Desktop
on:
    push:
        branches: [dev]
jobs:
    build_desktop:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
            - run: flutter config --enable-windows-desktop
            - run: flutter pub get
            - run: flutter build windows --release --dart-define=ENV=prod
            - run: flutter pub run msix:create --no-install-cert --config msix_config.yaml
            - uses: actions/upload-artifact@v4
              with:
                  path: build/windows/x64/runner/Release/*.msix
            - uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/windows/x64/runner/Release/*.msix
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
