name: Dev Cleanup
on:
  workflow_run:
    workflows: ["Dev Distribute"]
    types: [completed]

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Download Status
        uses: actions/download-artifact@v4
        with:
          name: release-status
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Check if Cleanup Needed
        id: check
        run: |
          status=$(cat release_status.txt)
          echo "status=$status" >> $GITHUB_OUTPUT

      - name: Run Cleanup Script
        if: steps.check.outputs.status == 'new_release=true'
        env:
          FIREBASE_PROJECT_NUMBER: "138886686943"
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          pip install requests
          python .github/scripts/cleanup_firebase.py
