name: Distribute App
on:
  push:
    branches: [test]
    # branches: [prod, dev]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - uses: actions/cache@v4
        with:
          path: ~/.config/shorebird
          key: ${{ runner.os }}-shorebird
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash"
      - uses: shorebirdtech/setup-shorebird@v1

      - id: check_type
        run: |
          if shorebird patch android --flavor ${{ github.ref_name }} --dry-run; then
             echo "is_new_release=false" >> $GITHUB_OUTPUT
             echo "new_release=false" > release_status.txt
             shorebird patch android --flavor ${{ github.ref_name }} --target lib/main.dart -- --dart-define=ENV=${{ github.ref_name }}
           else
             echo "Patch failed or native changes detected. Checking if release exists..."
             CURRENT_VER=$(grep 'version:' pubspec.yaml | sed 's/version: //')
             if shorebird release android --flavor ${{ github.ref_name }} --dry-run; then
               echo "is_new_release=true" >> $GITHUB_OUTPUT
               echo "new_release=true" > release_status.txt
               shorebird release android --flavor ${{ github.ref_name }} --artifact apk --target lib/main.dart -- --dart-define=ENV=${{ github.ref_name }}
             else
               echo "Error: Release $CURRENT_VER already exists and Patch is not possible due to Native changes."
               echo "Action required: Please bump the version in pubspec.yaml"
               exit 1
             fi
           fi
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
      - if: steps.check_type.outputs.is_new_release == 'true'
        uses: actions/cache/save@v4
        with:
          path: release_flag.txt
          key: cache-release-flag-${{ github.run_id }}
      - if: steps.check_type.outputs.is_new_release == 'true'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_ADMIN_SDK }}
          groups: "apk"
          file: ${{ github.ref_name == 'prod' && 'build/app/outputs/flutter-apk/app-prod-release.apk' || 'build/app/outputs/flutter-apk/app-dev-release.apk' }}
          releaseNotes: "new"
      - if: steps.check_type.outputs.is_new_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          files: build/app/outputs/flutter-apk/*.apk
          draft: false
          prerelease: ${{ github.ref_name == 'dev' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: find_apk
        if: steps.check_type.outputs.is_new_release == 'true'
        run: |
          APK_PATH=$(find build/app/outputs/flutter-apk -name "app-*-release.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "Error: APK file not found!"
            exit 1
          fi
          echo "Found APK at: $APK_PATH"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
      - id: get_version
        run: |
          RAW_VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | xargs)
          CLEAN_VERSION=$(echo $RAW_VERSION | cut -d '+' -f 1)
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT
      - if: steps.check_type.outputs.is_new_release == 'true'
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          sed -i "s/sparkle:version=\"[^\"]*\"/sparkle:version=\"$VERSION\"/g" android_appcast.xml
          APK_URL="https://github.com/${{ github.repository }}/releases/download/v$VERSION/app-release.apk"
          sed -i "s|url=\"[^\"]*\"|url=\"$APK_URL\"|g" android_appcast.xml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin prod --rebase
          git add android_appcast.xml
          git commit -m "chore: update appcast to $VERSION [skip ci]"
          git push
