name: CI/CD Pipeline (Powered by DevOps Core)

on:
    push:
        branches: [dev, main]
    workflow_dispatch:

jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/main.yml@prod
        secrets: inherit
