name: Distribute Desktop (Main)

on:
    push:
        branches: [test]
        # branches: [prod, dev, test]

jobs:
    # المرحلة الأولى: البناء والذكاء
    build_job:
        uses: ./.github/workflows/_build_logic.yml
        secrets: inherit

    # المرحلة الثانية: التوزيع (تعتمد على الأولى)
    distribute_job:
        needs: build_job
        uses: ./.github/workflows/_distribute_logic.yml
        with:
            version: ${{ needs.build_job.outputs.full_version }}
            file_name: ${{ needs.build_job.outputs.final_file_name }}
        secrets: inherit
