name: ⚙️ Setup Env
on:
    workflow_call:
jobs:
    setup:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shorebirdtech/setup-shorebird@v1
              with:
                  cache: true
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
            - run: shorebird upgrade
            - run: flutter pub get
            - run: git config --system core.longpaths true
